POST http://localhost:5000/create_account
content-type: application/json

{
    "password": "kuzka",
    "firstName": "Jakub",
    "lastName": "Pelec",
    "balance": 200,
    "email": "dadsdsddasdass@gmail.com",
    "PESEL": "NAURAcurrentNumberString"
}